TempTester: Tempature.class TempTester.class

Tempature.class: Tempature.java
	javac -deprecation Tempature.java

TempTester.class: TempTester.java
	javac -deprecation TempTester.java

clean:
	rm -f *.class *~ *# *.o

